// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader': string;
  'loader-dot': string;
  'loader-dots': string;
  'scale-dot': string;
}
declare var cssExports: CssExports;
export = cssExports;
